<?php
/**
 * © Anton Zelenski 2012
 * zelibobla@gmail.com
 *
 */
?>
<? if( !count( $this->items ) ) :?>
	<h2>Пока что нет пользователей</h2>
<? else : ?>
	<? if( !$this->no_layout ) :?>
		<div class="users_layout">
				<table id="items_table"
					   resource="user"
					   edit_url="/user/index/edit"
					   delete_url="/user/index/delete"
					   edit_class="item_edit"
					   delete_class="item_delete">
					<caption>Пользователи</caption>
					<thead>
						<tr>
							<th>имя</th>
							<th>email</th>
							<td></td>
						</tr>
					</thead>
					<tbody>
	<? endif ?>
					<? foreach( $this->items as $i ) :?>
						<tr item_name="<?=$i->getName()?>" item_id="<?=$i->getId()?>">
							<td><?=$i->getName()?></td>
							<td><?=$i->getEmail()?></td>
							<td class="controls">
								<button class="item_edit edit"><div class="icon"></div></button>
								<button class="item_delete delete"><div class="icon"></div></button>
							</td>
						</tr>
					<? endforeach ?>
	<? if( !$this->no_layout ) :?>
					</tbody>
				</table>
				<?=$this->paginationControl( $this->items )?>
			<button class="item_edit add"><div class="icon"></div></button>
		</div>
	<? endif ?>
<? endif ?>