<?php
/**
 * © Anton Zelenski 2012
 * zelibobla@gmail.com
 *
 */
?>
<div class="users_layout">
	<? if( count( $this->items ) ) :?>
		<table>
			<caption>Пользователи</caption>
			<thead>
				<tr>
					<th>имя</th>
					<th>email</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<? foreach( $this->items as $i ) :?>
					<tr item_name="<?=$i->getName()?>" id="<?=$i->getId()?>">
						<td><?=$i->getName()?></td>
						<td><?=$i->getEmail()?></td>
						<td class="controls">
							<button class="item">редактировать</button>
							<button class="delete"><div class="icon"></div>удалить</button>
						</td>
					</tr>
				<? endforeach ?>
			</tbody>
		</table>
		<?=$this->paginationControl( $this->items )?>
	<? else : ?>
		<h2>Пока что нет пользователей</h2>
	<? endif ?>
	<button class="item add"><div class="icon"></div>Добавить</button>
</div>