<?php
/**
 * © Anton Zelenski 2012
 * zelibobla@gmail.com
 *
 */

$defaults = Zend_Registry::get( 'defaults' );
?>
<?=$this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?
		$this->headLink()
			->appendStylesheet( '/css/global.css' )
			->appendStylesheet( '/js/jquery-ui-1.8.16.custom/css/custom-theme/jquery-ui-1.8.16.custom.css' )

			->appendStylesheet( '/css/chosen.css' )
			->headLink( array( 	'rel' => 'favicon',
	              				'href' => '/img/favicon.ico' ),
	              				'PREPEND' );

		$this->headScript()->prependFile( '/js/jquery.json/jquery.json-2.2.min.js', 'text/javascript' )
						   ->prependFile( '/js/jquery-ui-1.8.16.custom/js/jquery-ui-1.8.16.custom.min.js', 'text/javascript' )
						   ->prependFile( '/js/jquery-ui-1.8.16.custom/js/jquery-1.6.2.min.js', 'text/javascript' )
							 
						   ->appendFile( '/js/modules/core.js', 'text/javascript' )
						   ->appendFile( '/js/widgets/system_voice.js', 'text/javascript' )
						   ->appendFile( '/js/widgets/edit_item.js', 'text/javascript' )
						   ->appendFile( '/js/translator.js', 'text/javascript' );

		$request = Zend_Controller_Front::getInstance()->getRequest();
		$module = $request->getModuleName();
		$controller = $request->getControllerName();
		$action = $request->getParam( 'action' );
		if( is_file( APPLICATION_PATH . "/../public/css/modules/$module.css" ) ){
			$this->headLink()->appendStylesheet( "/css/modules/$module.css" );
		}
		if( is_file( APPLICATION_PATH . "/../public/js/modules/$module.js" ) ){
			$this->headScript()->appendFile( "/js/modules/$module.js" );
		}
		if( is_file( APPLICATION_PATH . "/../public/js/modules/{$module}_{$controller}.js" ) ){
			$this->headScript()->appendFile( "/js/modules/{$module}_{$controller}.js" );
		}
	
		echo $this->headTitle() .
	 		 $this->headMeta() .
			 $this->headLink() .
			 $this->headScript();
		
	?>
	<script type="text/javascript">
		var Core = function(){
			var _user = <?=json_encode( $this->user->getOptions() )?>,
				_route = <?=json_encode( array( 'module' => $module, 'controller' => $controller, 'action' => $action ) )?>,
				_resource = '<?=$this->resource?>';
			this.getUser = function(){
				return _user;
			}
			this.getRoute = function(){
				return _route;
			}
			this.getResource = function(){
				return _resource;
			}
		}
		var core = new Core();
	</script>
</head>
<body>

	<div class="wrapper">
		<div class="menu">
			<?	if( 'guest' != $this->user->getRole() ) :?>
				<div class="user_name">Добро пожаловать, <?=$this->htmlLink( $this->user )?>!</div>
			<? endif ?>
			<?=$this->navigation()->menu()->setPartial( array( 'menu.phtml', 'core' ) )->menu()?>
		</div>
		<div class="content"><?=$this->layout()->content?></div>
		<div class="push"></div>
	</div>
	<div class="footer">
		&copy; <?=$defaults[ 'application_name' ]?> <?=date( 'Y' )?>
	</div>
</body>
</html>
