<?php
/**
 * © Anton Zelenski 2012
 * zelibobla@gmail.com
 *
 */
$u = $this->item;
?>
<div class="user_profile">
	<h1><?=sprintf( $this->t( 'user_profile_header' ), $u->__toString() )?></h1>
	<ul class="properties_list">
		<li>
			<label></label>
			<div><?=$this->icon( $u )?></div>
		</li>
		<li>
			<label><?=$this->t( 'user_name' )?></label>
			<div><?=$u?></div>
		</li>
		<? if( $u->getId() == $this->user->getId() ) :?>
			<li>
				<label></label>
				<div><a href="<?=$this->url( array(), 'user_profile_edit' )?>"><?=$this->t( 'edit' )?></a></div>
			</li>
			<li>
				<label></label>
				<div><a href="<?=$this->url( array(), 'user_change_password' )?>"><?=$this->t( 'user_change_password' )?></a></div>
			</li>
		<? endif ?>
	</ul>
</div>
<div class="clear"></div>
