<?
/**
 * © Anton Zelenski 2012
 * zelibobla@gmail.com
 *
 */
$t = Zend_Registry::get( 'translator' );
$acl = $this->navigation()->getAcl();
$role = $this->navigation()->getRole();
$current_route = Zend_Controller_Front::getInstance()->getRouter()->getCurrentRouteName();
if( count( $this->container ) ){
	$html = "";
	foreach( $this->container as $page ){
		if( true == ( $resource = $page->getResource() ) &&
			true == ( $privilege = $page->getPrivilege() ) &&
			false == $acl->isAllowed( $role, $resource, $privilege ) ) continue;
		$route = $page->getRoute();
		$class = $route == $current_route ? "active " . $route : $route;
		$menu_item = '';
		$submenu = '';
		$show_submenu = false;
		if( 'home' == $route ){
			$menu_item = '<a href="' . $this->url( array(), $route ) . '"><div class="icon_' . $route . '"></div></a>';
		} elseif( false !== strpos( $class, 'active' ) ) {
			$menu_item = $t->_( $page->getLabel() );
		} else {
			$menu_item = '<a href="' . $this->url( array(), $page->getRoute() ) . '">' . $t->_( $page->getLabel() ) . '</a>';
		}
		$pages = $page->getPages();
		if( !empty( $pages ) ){
			$show_submenu = 'active' == $class;
			$submenu = '<ul>';
			foreach( $pages as $subpage ){
				if( $subpage->getRoute() == $current_route ){
					$show_submenu = true;
					$submenu .= '<li class="active">' . $t->_( $subpage->getLabel() ) . '</li>';
				} else {
					$submenu .= '<li><a href="' . $this->url( array(), $subpage->getRoute() ) . '">' . $t->_( $subpage->getLabel() ) . '</li>';
				}
			
			}
			$submenu .= '</ul>';
		}
		$html .= '<li class="' . $class . '">
					<div class="menu_item">' . $menu_item . '</div>' .
					( $show_submenu ? $submenu : '' ) .
				 '</li>';
	}
	echo $html ? '<ul class="navigation">' . $html . '</ul>' : '';
}

